packages:
  - 'tests'
  - 'packages/blocks'
  - 'packages/docs'
  - 'packages/playground'
  - 'packages/presets'
  - 'packages/framework/*'
  - 'packages/affine/*'

catalog:
  '@blocksuite/icons': ^2.1.67
  '@toeverything/theme': ^1.0.8
  '@toeverything/y-indexeddb': 0.10.0-canary.9

  '@preact/signals': ^1.3.0
  '@preact/signals-core': ^1.8.0
  '@lit-labs/preact-signals': ^1.0.2
  '@lit/context': ^1.1.2
  lit: ^3.2.0

  zod: ^3.23.8
  minimatch: ^10.0.1
  nanoid: ^5.0.7
  date-fns: ^3.6.0

  y-indexeddb: ^9.0.12
  y-protocols: ^1.0.6
  yjs: ^13.6.18
  lib0: ^0.2.97

  '@floating-ui/dom': ^1.6.10
  '@lottiefiles/dotlottie-wc': ^0.2.16
